version: '3.4'

services:
  miaticket.webapi:
    image: ${DOCKER_REGISTRY-}miaticketwebapi
    build:
      context: .
      dockerfile: MiaTicket.WebAPI/Dockerfile
  miaticket.redis:
    image: redis:latest
    container_name: miaticket.redis
    restart: always
    ports:
    - '6379:6379'
      